import test from 'node:test';import assert from 'node:assert/strict';import {TapRouter} from '../interaction-flow.mjs';import {GestureEngine,describeHand} from '../gestures.mjs';import {Manipulator} from '../manipulation.mjs';
const h=(id=1,extra={})=>({id,px:.4,py:.5,x:.4,y:.5,wx:.4,wy:.6,pinch:1,open:true,down:false,fist:false,depthSize:.15,depthQuality:1,depthShape:1,...extra});
const base=()=>({x:0,y:0,z:0,scale:1,rotation:0,tilt:0,roll:0});
test('UI taps work from either hand while another hand is visible',()=>{for(const owner of [1,2]){const t=new TapRouter(),hs=[h(1,{actionId:owner===1?'mode-dual':null}),h(2,{actionId:owner===2?'mode-dual':null})];assert.deepEqual(t.update(hs,[{type:'pinch',id:owner}],0),[]);assert.deepEqual(t.update(hs,[{type:'release',id:owner}],100),[{type:'tap',target:'mode-dual',id:owner}]);}});
test('a slow deliberate UI pinch is accepted once after release',()=>{const t=new TapRouter(),hs=[h(1,{actionId:'mode-rotate'})];t.update(hs,[{type:'pinch',id:1}],0);for(let at=100;at<=4000;at+=100)assert.deepEqual(t.update(hs,[],at),[]);assert.equal(t.update(hs,[{type:'release',id:1}],4100)[0].target,'mode-rotate');assert.deepEqual(t.update(hs,[{type:'release',id:1}],4150),[]);});
test('other hand loss cannot cancel an owned UI tap but owner loss does',()=>{const t=new TapRouter(),owner=h(2,{actionId:'stop'});t.update([h(),owner],[{type:'pinch',id:2}],0);t.update([owner],[{type:'lost',id:1},{type:'cancel'}],50);assert.equal(t.update([owner],[{type:'release',id:2}],100)[0].target,'stop');t.update([owner],[{type:'pinch',id:2}],400);t.update([],[{type:'lost',id:2}],450);assert.deepEqual(t.update([owner],[{type:'release',id:2}],500),[]);});
test('moderate palm drift is tolerated, a deliberate large UI drag is cancelled',()=>{for(const [travel,accepted]of [[.07,true],[.14,false]]){const t=new TapRouter();t.update([h(1,{actionId:'mode-dual'})],[{type:'pinch',id:1}],0);const result=t.update([h(1,{px:.4+travel})],[{type:'release',id:1}],100);assert.equal(result.length,accepted?1:0);}});
test('a first object pinch can start with a second open hand already visible',()=>{const t=new TapRouter();assert.deepEqual(t.update([h(1,{hoverId:'single'}),h(2)],[{type:'pinch',id:1}],0),[{type:'grab',target:'single',id:1}]);});
test('two simultaneous object pinches acquire one target, never two transformations',()=>{const t=new TapRouter();const r=t.update([h(1,{hoverId:'single'}),h(2,{hoverId:'panel'})],[{type:'pinch',id:1},{type:'pinch',id:2}],0);assert.equal(r.length,1);assert.equal(r[0].target,'single');});
test('UI input takes precedence over an object pinch from another hand',()=>{const t=new TapRouter();assert.deepEqual(t.update([h(1,{hoverId:'single'}),h(2,{actionId:'mode-dual'})],[{type:'pinch',id:1},{type:'pinch',id:2}],0),[]);assert.equal(t.press.id,2);});
test('a moderate closure and release can produce one complete tap',()=>{const g=new GestureEngine(),raw=pinch=>({x:.4,y:.5,wx:.4,wy:.6,pinch,open:true});g.update([raw(1)],0);g.update([raw(1)],50);assert.ok(g.update([raw(.36)],83).events.some(e=>e.type==='pinch'));assert.ok(g.update([raw(.47)],116).events.some(e=>e.type==='release'));});
test('one grabbed hand still moves with an open or relaxed second hand present',()=>{for(const fist of [false,true]){const m=new Manipulator();let state=base();m.update([h(1,{down:true}),h(2,{px:.8,fist})],33,{state,key:'single',operation:'dual'});const r=m.update([h(1,{down:true,px:.42}),h(2,{px:.8,fist})],66,{state,key:'single',operation:'dual'});assert.equal(r.phase,'drag');assert.ok(r.state.x>0);assert.equal(r.state.rotation,0);}});
test('swipe inertia lasts beyond old 220ms brake, while stop and loss remain immediate',()=>{const m=new Manipulator();let state=base(),time=0;function tick(x,empty=false){time+=33;const r=m.update(empty?[]:[h(1,{px:x})],time,{state,key:'single',operation:'rotate'});if(r.state)state=r.state;return r;}tick(.3);for(let i=1;i<=5;i++)tick(.3+i*.015);const start=state.rotation;for(let i=0;i<30;i++)tick(.375+(i%2?.0004:-.0004));assert.ok(state.rotation>start+1);tick(.375,true);const old={...state};tick(.375,true);assert.deepEqual(state,old);m.stop();tick(.7);assert.deepEqual(state,old);});


test('curled-finger pinch is not simultaneously classified as a stop fist',()=>{const p=Array.from({length:21},()=>({x:.5,y:.8,z:0}));p[5]={x:.4,y:.65,z:0};p[17]={x:.6,y:.65,z:0};p[9]={x:.5,y:.65,z:0};p[6]={x:.4,y:.7,z:0};p[8]={x:.5,y:.78,z:0};p[4]={x:.572,y:.78,z:0};const hand=describeHand(p);assert.ok(hand.pinch>.34&&hand.pinch<.38);assert.equal(hand.fist,false);});

test('arming requires a continuous open interval before the first pinch',()=>{const g=new GestureEngine(),raw=pinch=>({x:.4,y:.5,wx:.4,wy:.6,pinch,open:true});g.update([raw(.47)],0);g.update([raw(.42)],30);g.update([raw(.47)],60);assert.equal(g.update([raw(.36)],70).events.some(e=>e.type==='pinch'),false);g.update([raw(.47)],80);g.update([raw(.47)],125);assert.ok(g.update([raw(.36)],160).events.some(e=>e.type==='pinch'));});
