import test from 'node:test';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {Manipulator} from '../manipulation.mjs';import {PalmDepthCue} from '../depth-controller.mjs';
const h=(id=1,x=.35,extra={})=>({id,px:x,py:.5,down:true,open:false,fist:false,depthSize:.15,depthQuality:1,depthShape:1,...extra});
const base=()=>({x:0,y:0,z:0,scale:1,rotation:0,tilt:0,roll:0});
const near=(a,b,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
function session(operation='dual'){const m=new Manipulator();let s=base(),time=0;return {m,get s(){return s;},tick(hs,ms=33,op=operation){time+=ms;const r=m.update(hs,time,{state:s,key:'single',aspect:1.6,operation:op});if(r.state)s=r.state;return r;},warm(hs){for(let i=0;i<8;i++)this.tick(hs);}};}
test('near hand gives positive z, larger perspective; far reverses without changing scale',()=>{const s=session('place');s.warm([h()]);for(let i=1;i<=12;i++)s.tick([h(1,.35,{depthSize:.15*Math.exp(i*.018)})]);assert.ok(s.s.z>.8);near(s.s.scale,1);assert.ok(5.8/(5.8-s.s.z)>1.15);for(let i=11;i>=-8;i--)s.tick([h(1,.35,{depthSize:.15*Math.exp(i*.018)})]);assert.ok(s.s.z<-.5);near(s.s.scale,1);});
test('stationary hands settle without drift and release keeps all transforms',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=8;i++)s.tick([h(1,.35+i*.003,{depthSize:.15*Math.exp(i*.02)}),h(2,.65+i*.003,{depthSize:.15*Math.exp(i*.02)})]);const hs=[h(1,.374,{depthSize:.15*Math.exp(.16)}),h(2,.674,{depthSize:.15*Math.exp(.16)})];for(let i=0;i<12;i++)s.tick(hs);const old={...s.s};for(let i=0;i<60;i++)s.tick(hs);assert.deepEqual(s.s,old);s.tick([]);assert.deepEqual(s.s,old);});
test('dual centroid translates XY without changing orientation or zoom',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=12;i++)s.tick([h(1,.35+i*.003,{py:.5-i*.002}),h(2,.65+i*.003,{py:.5-i*.002})]);assert.ok(s.s.x>.2&&s.s.y>.1);near(s.s.scale,1);near(s.s.rotation,0);near(s.s.roll,0);near(s.s.z,0);});
test('common depth excludes perspective spread from zoom',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=15;i++){const size=Math.exp(i*.018);s.tick([h(1,.5-.15*size,{depthSize:.15*size}),h(2,.5+.15*size,{depthSize:.15*size})]);}assert.ok(s.s.z>1);assert.ok(Math.abs(s.s.scale-1)<.025);near(s.s.rotation,0);});
test('opposed depth rotates in the direction of the nearer hand, with fixed centroid and zoom',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=12;i++)s.tick([h(1,.35,{depthSize:.15*Math.exp(-i*.012)}),h(2,.65,{depthSize:.15*Math.exp(i*.012)})]);assert.ok(s.s.rotation<-.6);near(s.s.z,0,1e-6);near(s.s.scale,1);near(s.s.x,0);for(let i=11;i>=-12;i--)s.tick([h(1,.35,{depthSize:.15*Math.exp(-i*.012)}),h(2,.65,{depthSize:.15*Math.exp(i*.012)})]);assert.ok(s.s.rotation>.6);});
test('spread scales while common depth and orientation remain fixed',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=12;i++)s.tick([h(1,.35-i*.004),h(2,.65+i*.004)]);assert.ok(s.s.scale>1.25);near(s.s.rotation,0);near(s.s.z,0);near(s.s.x,0);});
test('depth rotation direction is independent of which side receives first track ID',()=>{const s=session();s.warm([h(1,.65),h(2,.35)]);for(let i=1;i<=12;i++)s.tick([h(1,.65,{depthSize:.15*Math.exp(i*.012)}),h(2,.35,{depthSize:.15*Math.exp(-i*.012)})]);assert.ok(s.s.rotation<-.6);});
test('tilting the connecting line rolls the object without zoom for constant span',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=12;i++){const a=i*.025;s.tick([h(1,.5-.15*Math.cos(a),{py:.5+.24*Math.sin(a)}),h(2,.5+.15*Math.cos(a),{py:.5-.24*Math.sin(a)})]);}near(s.s.roll,.3,1e-6);near(s.s.scale,1);near(s.s.rotation,0);});
test('mode and one/two hand transitions and detector order changes do not jump',()=>{const s=session();s.warm([h()]);let old={...s.s};s.tick([h(),h(2,.8)]);assert.deepEqual(s.s,old);s.warm([h(),h(2,.8)]);old={...s.s};s.tick([h(2,.8),h()]);assert.deepEqual(s.s,old);s.tick([h()]);assert.deepEqual(s.s,old);s.tick([h(1,.7,{open:true,down:false})],33,'rotate');assert.deepEqual(s.s,old);});
test('tracking loss, long gap and large position discontinuity freeze and rebase',()=>{for(const kind of ['loss','gap','jump','identity']){const s=session();s.warm([h(),h(2,.65)]);const old={...s.s};if(kind==='loss')s.tick([]);if(kind==='gap')s.tick([h(),h(2,.65)],400);if(kind==='jump')s.tick([h(1,.7),h(2,.9)]);if(kind==='identity')s.tick([h(3,.4),h(4,.7)]);assert.deepEqual(s.s,old,kind);}});
test('palm mode needs no pinch or hit area and inertia stops on loss or explicit stop',()=>{const s=session('rotate');s.warm([h(1,.35,{down:false,open:true})]);for(let i=1;i<=6;i++)s.tick([h(1,.35+i*.01,{down:false,open:true})]);assert.ok(s.s.rotation>.3);const r=s.tick([h(1,.41,{down:false,open:true})]);assert.equal(r.phase,'coasting');s.tick([]);const old={...s.s};s.tick([]);assert.deepEqual(s.s,old);s.m.stop();s.tick([h(1,.8,{down:false,open:true})]);assert.deepEqual(s.s,old);});
test('pinch movement never coasts or rotates even in palm mode',()=>{const s=session('rotate');s.warm([h(1,.35,{down:false,open:true})]);s.tick([h(1,.4,{down:false,open:true})]);s.tick([h(1,.4)]);const old={...s.s};s.tick([h(1,.42)]);near(s.s.rotation,old.rotation);assert.ok(s.s.x>old.x);});
test('corrected moderate palm tilt and rejected oblique palms do not move depth',()=>{const cue=new PalmDepthCue();for(let t=0;t<=264;t+=33)cue.update(h(),t);let sum=0;for(let i=1;i<=12;i++){const q=1-i*.01;sum+=cue.update(h(1,.35,{depthQuality:q,depthSize:.15*Math.sqrt(q)}),264+i*33).delta;}near(sum,0);assert.equal(cue.update(h(1,.35,{depthQuality:.6,depthSize:.1}),700).valid,false);});
test('size jumps are rejected and reacquisition starts at current depth',()=>{const s=session('place');s.warm([h()]);const old={...s.s};s.tick([h(1,.35,{depthSize:.3})]);assert.deepEqual(s.s,old);s.warm([h(1,.35,{depthSize:.3})]);assert.deepEqual(s.s,old);});
test('hands meeting and crossing freeze until their axis can rebase',()=>{const s=session();s.warm([h(1,.48),h(2,.52)]);const old={...s.s};s.tick([h(1,.52),h(2,.48)]);s.tick([h(1,.57),h(2,.43)]);assert.deepEqual(s.s,old);});
test('uncertain dual depth cannot be misinterpreted as zoom during size or tracking discontinuity',()=>{const s=session();s.warm([h(),h(2,.65)]);for(let i=1;i<=8;i++)s.tick([h(1,.35-i*.004,{depthQuality:.5}),h(2,.65+i*.004,{depthQuality:.5})]);near(s.s.scale,1);near(s.s.z,0);});
test('separated hands swapping sides rebase depth direction without a position jump',()=>{const s=session();s.warm([h(1,.35,{py:.4}),h(2,.65,{py:.6})]);let held=false;for(let i=1;i<=12;i++){const before={...s.s},r=s.tick([h(1,.35+i*.025,{py:.4}),h(2,.65-i*.025,{py:.6})]);if(r.phase==='reacquire'){held=true;assert.deepEqual(s.s,before);}}assert.ok(held);s.warm([h(1,.65,{py:.4}),h(2,.35,{py:.6})]);const before=s.s.rotation;for(let i=1;i<=12;i++)s.tick([h(1,.65,{py:.4,depthSize:.15*Math.exp(i*.012)}),h(2,.35,{py:.6,depthSize:.15*Math.exp(-i*.012)})]);assert.ok(s.s.rotation<before-.5);});
test('fine stationary jitter does not cause rotation or depth drift',()=>{const s=session('rotate');s.warm([h(1,.35,{down:false,open:true})]);for(let i=0;i<100;i++)s.tick([h(1,.35+(i%2?1:-1)*.0003,{down:false,open:true})]);near(s.s.rotation,0);const d=session('place');d.warm([h()]);for(let i=0;i<100;i++)d.tick([h(1,.35,{depthSize:.15*(1+(i%2?1:-1)*.002)})]);near(d.s.z,0);});
test('controller responsiveness and throughput are measured with synthetic data',()=>{const s=session('place');s.warm([h()]);let response=null;for(let i=1;i<=12;i++){s.tick([h(1,.35,{depthSize:.15*Math.exp(i*.01)})]);if(response===null&&s.s.z>.02)response=i*33;}assert.ok(response<=99,`${response}ms`);const start=performance.now();for(let i=0;i<10000;i++)s.tick([h(1,.35+Math.sin(i*.01)*.01)]);const elapsed=performance.now()-start;writeFileSync(new URL('./results/v08-controller-timing.json',import.meta.url),JSON.stringify({synthetic:true,firstDepthResponseMs:response,iterations:10000,totalMs:elapsed,meanUpdateMs:elapsed/10000,physicalEndToEndLatencyMeasured:false},null,2));});

