import test from 'node:test';import assert from 'node:assert/strict';import {SummonGate,TapRouter} from '../interaction-flow.mjs';
const hand=(extra={})=>({id:1,open:true,down:false,fist:false,px:.5,py:.5,...extra});
const edge=(type,id=1)=>[{type,id}];
test('open palm requires all 3000ms, showing progress before ready',()=>{const g=new SummonGate();for(let t=0;t<3000;t+=100){const r=g.update([hand()],t,true);assert.equal(r.ready,false);assert.equal(r.progress,t/3000);}assert.equal(g.update([hand()],3000,true).ready,true);});
test('a closed hand, loss, disabled gate, or identity change restarts summon',()=>{for(const change of ['closed','missing','disabled','identity']){const g=new SummonGate();for(let t=0;t<=2800;t+=100)g.update([hand()],t,true);const hs=change==='missing'?[]:[hand(change==='closed'?{open:false}:change==='identity'?{id:2}:{})];assert.equal(g.update(hs,2900,change!=='disabled').ready,false);assert.equal(g.update([hand()],3000,true).ready,false);}});
test('camera timestamp gap cannot complete summon from stale observations',()=>{const g=new SummonGate();g.update([hand()],0,true);assert.equal(g.update([hand()],4000,true).progress,0);});
test('menu guard prevents opening hand or immediate pinch selecting an icon',()=>{const t=new TapRouter();t.guard(3000,450);assert.deepEqual(t.update([hand({actionId:'summon-whole'})],edge('pinch'),3100),[]);assert.deepEqual(t.update([hand({actionId:'summon-whole'})],edge('release'),3200),[]);assert.equal(t.press,null);});
test('single UI tap fires only once on release, never on pinch or hold',()=>{const t=new TapRouter(),h=hand({actionId:'reset'});assert.deepEqual(t.update([h],edge('pinch'),0),[]);for(let time=100;time<=400;time+=100)assert.deepEqual(t.update([h],[],time),[]);assert.deepEqual(t.update([h],edge('release'),500),[{type:'tap',target:'reset',id:1}]);assert.deepEqual(t.update([h],edge('release'),550),[]);});
test('release finger cursor drift does not change locked UI target',()=>{const t=new TapRouter();t.update([hand({actionId:'reset'})],edge('pinch'),0);const r=t.update([hand({actionId:'open-menu',px:.52})],edge('release'),150);assert.equal(r[0].target,'reset');});
test('a UI drag cancels instead of selecting a different icon',()=>{const t=new TapRouter();t.update([hand({actionId:'reset'})],edge('pinch'),0);t.update([hand({px:.64})],[],100);assert.deepEqual(t.update([hand({actionId:'open-menu'})],edge('release'),200),[]);});
test('object pinch immediately starts grab without prior double tap',()=>{const t=new TapRouter();assert.deepEqual(t.update([hand({hoverId:'single'})],edge('pinch'),0),[{type:'grab',target:'single',id:1}]);});
test('double object taps never change operation mode',()=>{const t=new TapRouter(),h=hand({hoverId:'single'});t.update([h],edge('pinch'),0);assert.deepEqual(t.update([h],edge('release'),100),[]);assert.equal(t.update([h],edge('pinch'),220)[0].type,'grab');assert.deepEqual(t.update([h],edge('release'),320),[]);});
test('a real object drag does not count toward double-tap rotation',()=>{const t=new TapRouter(),h=hand({hoverId:'single'});t.update([h],edge('pinch'),0);t.update([hand({hoverId:'single',px:.54})],[],100);t.update([h],edge('release'),200);t.update([h],edge('pinch'),320);assert.deepEqual(t.update([h],edge('release'),420),[]);});
test('a long grab does not arm rotation',()=>{const t=new TapRouter(),h=hand({hoverId:'single'});t.update([h],edge('pinch'),0);for(let time=100;time<=900;time+=100)t.update([h],[],time);t.update([h],edge('release'),1000);t.update([h],edge('pinch'),1120);assert.deepEqual(t.update([h],edge('release'),1240),[]);});
test('different targets, missing hands or a second hand cannot finish a double tap',()=>{for(const type of ['target','loss','two']){const t=new TapRouter(),h=hand({hoverId:'single'});t.update([h],edge('pinch'),0);t.update([h],edge('release'),100);if(type==='loss')t.update([],edge('lost'),180);if(type==='two')t.update([h,hand({id:2})],[],180);const n=hand({hoverId:type==='target'?'panel':'single'});t.update([n],edge('pinch'),220);assert.deepEqual(t.update([n],edge('release'),320),[]);}});
test('UI takes priority when projected panel button overlaps a grab area',()=>{const t=new TapRouter(),h=hand({actionId:'open-menu',hoverId:'panel'});assert.deepEqual(t.update([h],edge('pinch'),0),[]);assert.equal(t.update([h],edge('release'),100)[0].type,'tap');});
test('a new mouse action clears stale hand press while allowing the next fresh tap',()=>{const t=new TapRouter(),h=hand({actionId:'reset'});t.update([h],edge('pinch'),0);t.guard(50,120);assert.deepEqual(t.update([h],edge('release'),100),[]);t.update([h],edge('pinch'),220);assert.equal(t.update([h],edge('release'),320)[0].target,'reset');});
test('a captured 30fps one-frame tap is accepted without asking the user to hold',()=>{const t=new TapRouter(),h=hand({actionId:'open-menu'});t.update([h],edge('pinch'),0);assert.equal(t.update([h],edge('release'),33)[0].target,'open-menu');});


