import test from 'node:test';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';import {GestureEngine,describeHand} from '../gestures.mjs';import {Manipulator} from '../manipulation.mjs';
const h=(id,x,extra={})=>({id,x,y:.4,px:x,py:.5,wx:x,wy:.65,pinch:.7,open:true,palmOpen:true,down:false,fist:false,depthSize:.15,depthShape:1,depthQuality:1,...extra});
test('tracking grace holds identity without outputting fabricated landmarks',()=>{const g=new GestureEngine({graceMs:180});g.update([h(1,.3)],0);g.update([h(1,.3)],50);const held=g.update([h(1,.3,{pinch:.2})],80).hands[0];assert.ok(held.down);const missing=g.update([],100);assert.equal(missing.hands.length,0);assert.ok(missing.events.some(e=>e.type==='missing'));const r=g.update([h(1,.32,{pinch:.2})],200);assert.equal(r.hands[0].id,held.id);assert.ok(r.hands[0].down);assert.ok(r.events.some(e=>e.type==='reacquired'));assert.ok(!r.events.some(e=>e.type==='pinch'));g.update([],220);assert.ok(g.update([],420).events.some(e=>e.type==='lost'));const fresh=g.update([h(1,.32,{pinch:.2})],440);assert.equal(fresh.hands[0].down,false);});
test('confident handedness preserves IDs through detector reorder and crossing',()=>{const g=new GestureEngine({graceMs:180});const pair=(x,y)=>[h(1,x,{handLabel:'Left'}),h(2,y,{handLabel:'Right'})];const first=g.update(pair(.3,.7),0).hands;for(let i=1;i<=20;i++){let hs=pair(.3+i*.02,.7-i*.02);if(i%2)hs.reverse();const got=g.update(hs,i*33).hands;for(const old of first)assert.equal(got.find(h=>h.handLabel===old.handLabel).id,old.id);}});
test('palm description ignores thumb/index articulation for palm controls',()=>{const p=Array.from({length:21},()=>({x:.5,y:.8,z:0}));p[5]={x:.4,y:.6,z:0};p[9]={x:.47,y:.57,z:0};p[13]={x:.53,y:.6,z:0};p[17]={x:.6,y:.63,z:0};for(const [tip,pip] of [[12,10],[16,14],[20,18]]){p[pip]={x:.5,y:.5,z:0};p[tip]={x:.5,y:.4,z:0};}p[8]={x:.4,y:.3,z:0};p[4]={x:.2,y:.3,z:0};const a=describeHand(p);p[4]={...p[8]};const b=describeHand(p);for(const k of ['px','py','palmYaw','palmPitch','palmRoll','palmOpen'])assert.equal(a[k],b[k]);assert.equal(b.palmOpen,true);});
test('100 repeatable trajectories record start, switch, stop, retention and response metrics',()=>{const metrics={source:'synthetic observations; not physical camera',trials:100,palmStarts:0,unexpectedModeSwitches:0,stopFailures:0,retentionFailures:0,firstMotionResponseMs:[],controllerUpdateMs:[]};for(let n=0;n<100;n++){const m=new Manipulator();let state={x:0,y:0,z:0,scale:1,rotation:0,tilt:0,roll:0},time=0;const tick=(x,extra={})=>{time+=33;const start=performance.now(),r=m.update([h(1,x,{down:true,pinch:.1,...extra})],time,{state,key:'single',operation:'rotate'});metrics.controllerUpdateMs.push(performance.now()-start);if(r.state)state=r.state;return r;};for(let i=0;i<8;i++)tick(.3);const old={...state};for(let i=1;i<=8;i++){tick(.3+i*(.003+n*.00001));if(i===1&&state.rotation!==old.rotation)metrics.firstMotionResponseMs.push(33);}if(state.rotation>old.rotation)metrics.palmStarts++;if(state.x!==0||state.y!==0||state.z!==0||state.scale!==1)metrics.unexpectedModeSwitches++;const held={...state};for(let i=0;i<20;i++)tick(.3+8*(.003+n*.00001));if(JSON.stringify(state)!==JSON.stringify(held))metrics.stopFailures++;const g=new GestureEngine({graceMs:180});g.update([h(1,.3)],0);g.update([h(1,.3)],50);g.update([h(1,.3,{pinch:.2})],83);g.update([],116);if(!g.update([h(1,.3,{pinch:.2})],182).hands[0]?.down)metrics.retentionFailures++;}
const timings=metrics.controllerUpdateMs.sort((a,b)=>a-b);metrics.controllerUpdateMs={median:timings[Math.floor(timings.length*.5)],p95:timings[Math.floor(timings.length*.95)]};writeFileSync(new URL('./results/v10-repeat-metrics.json',import.meta.url),JSON.stringify(metrics,null,2));assert.equal(metrics.palmStarts,100);assert.equal(metrics.unexpectedModeSwitches,0);assert.equal(metrics.stopFailures,0);assert.equal(metrics.retentionFailures,0);assert.equal(metrics.firstMotionResponseMs.length,100);});

test('one visible hand out of two keeps the nearest identity, not the first slot',()=>{const g=new GestureEngine({graceMs:180});const first=g.update([h(1,.3),h(2,.45)],0).hands;const r=g.update([h(2,.45)],33);assert.equal(r.hands.length,1);assert.equal(r.hands[0].id,first[1].id);assert.ok(r.events.some(e=>e.type==='missing'&&e.id===first[0].id));const back=g.update([h(1,.3),h(2,.45)],66);assert.equal(back.hands.find(h=>h.wx===.3).id,first[0].id);});
test('ambiguous single observation between two hands freezes both identities',()=>{const g=new GestureEngine({graceMs:180});const initial=g.update([h(1,.4),h(2,.44)],0);const r=g.update([h(1,.42)],33);assert.equal(r.hands.length,0);assert.equal(r.events.filter(e=>e.type==='missing').length,2);const back=g.update([h(1,.4),h(2,.44)],66);assert.deepEqual(new Set(back.hands.map(h=>h.id)),new Set(initial.hands.map(h=>h.id)));});
