import test from 'node:test';import assert from 'node:assert/strict';import {OperatorGate,ClapResetGate} from '../interaction-flow.mjs';import {Manipulator} from '../manipulation.mjs';
const h=(x,extra={})=>({wx:1-x,wy:.5,px:1-x,py:.5,open:true,palmOpen:true,brakeCandidate:false,size:.15,depthQuality:1,points:[],...extra});
const pose=(a=.3,b=.7,c=.5)=>{const p=Array.from({length:33},()=>({x:c,y:.5,visibility:1}));p[11]={x:c-.1,y:.3,visibility:1};p[12]={x:c+.1,y:.3,visibility:1};p[15]={x:a,y:.5,visibility:1};p[16]={x:b,y:.5,visibility:1};return p;};
test('first clearest raised hand becomes main; unrelated hand never gets input',()=>{const g=new OperatorGate(),a=h(.3),b=h(.7,{size:.12}),visitor=h(.95,{size:.4});const r=g.update([visitor,b,a],pose(),0);assert.equal(r.length,1);assert.equal(r[0].personSlot,'Left');for(let t=33;t<600;t+=33)assert.equal(g.update([h(.7,{size:.4}),a],pose(),t)[0].personSlot,'Left');});
test('single hand mode ignores auxiliary pinch/fist and detector reorder',()=>{const g=new OperatorGate();g.update([h(.3),h(.7,{size:.1})],pose(),0);for(const extra of [{down:true},{closedPalm:true},{actionId:'mode-rotate'}]){const r=g.update([h(.7,extra),h(.3)],pose(),33);assert.equal(r.length,1);assert.equal(r[0].personSlot,'Left');}});
test('both modes permit only same-pose hands, main first',()=>{const g=new OperatorGate();g.update([h(.3)],pose(),0);const r=g.update([h(.95),h(.7),h(.3)],pose(),33,{dual:true});assert.deepEqual(r.map(x=>x.personSlot),['Left','Right']);});
test('missing main cannot hand control to remaining hand',()=>{const g=new OperatorGate();g.update([h(.3)],pose(),0);assert.deepEqual(g.update([h(.7)],pose(),33,{dual:true}),[]);});
test('missing body and low visibility freeze',()=>{const g=new OperatorGate();assert.deepEqual(g.update([h(.3)],null,0),[]);const p=pose();p[11].visibility=.2;assert.deepEqual(g.update([h(.3)],p,33),[]);});
test('person jump latches closed until explicit reset',()=>{const g=new OperatorGate();g.update([h(.3)],pose(),0);assert.deepEqual(g.update([h(.8)],pose(.8,.9,.8),33),[]);assert.ok(g.blocked);assert.deepEqual(g.update([h(.3)],pose(),66),[]);g.reset();assert.equal(g.update([h(.3)],pose(),99).length,1);});
test('ambiguous multiple hands at operator wrist freeze rather than adopt visitor',()=>{const g=new OperatorGate();g.update([h(.3)],pose(),0);assert.deepEqual(g.update([h(.3),h(.31)],pose(),33),[]);});
test('panel never acquires rotation under any hand operation',()=>{for(const operation of ['rotate','dual','inspect','place','depth']){const m=new Manipulator();let state={x:0,y:0,z:0,scale:1,rotation:1,tilt:1,roll:1};for(let i=0;i<20;i++){const hs=[h(.3+i*.002,{id:1,down:true,pinch:.1,depthSize:.15,depthShape:1}),h(.7-i*.002,{id:2,down:true,pinch:.1,depthSize:.15,depthShape:1})];const r=m.update(hs,i*33+1,{key:'panel',state,operation});if(r.state)state=r.state;}assert.equal(state.rotation,0);assert.equal(state.tilt,0);assert.equal(state.roll,0);}});
const pair=d=>[h(.5-d/2),h(.5+d/2)];
test('one visual clap fires once only in bimanual mode',()=>{const c=new ClapResetGate();const ds=[.4,.38,.30,.2,.1,.04];let events=0;ds.forEach((d,i)=>{if(c.update(pair(d),i*33,true))events++;});assert.equal(events,1);for(let i=0;i<12;i++)assert.equal(c.update(pair(.04),250+i*33,true),false);});
test('clap disabled outside both-hand mode, pinched zoom and slow closing never reset',()=>{for(const mode of ['single','pinch','slow']){const c=new ClapResetGate();for(let i=0;i<25;i++){const ds=mode==='slow'?.4-i*.014:[.4,.3,.2,.1,.04][Math.min(i,4)];const hs=pair(ds).map(h=>({...h,down:mode==='pinch'}));assert.equal(c.update(hs,i*(mode==='slow'?100:33),mode!=='single'),false);}}});
test('hands initially touching and missing observations cannot trigger reset',()=>{const c=new ClapResetGate();for(let t=0;t<500;t+=33)assert.equal(c.update(pair(.04),t,true),false);assert.equal(c.update([],550,true),false);});

test('long person loss and slow drift cannot silently transfer ownership',()=>{const g=new OperatorGate();g.update([h(.3)],pose(),0);g.update([],null,800);assert.ok(g.blocked);assert.deepEqual(g.update([h(.3)],pose(),833),[]);const n=new OperatorGate();for(let i=0;i<7;i++)n.update([h(.3+i*.05)],pose(.3+i*.05,.7+i*.05,.5+i*.05),i*100);assert.ok(n.blocked);});
test('clap distance uses the same aspect scale as palm size',()=>{const c=new ClapResetGate();let fired=false;for(const [i,d] of [.28,.23,.18,.12,.06,.02].entries()){const hs=pair(d).map(h=>({...h,size:.21}));if(c.update(hs,i*33,true,1.777))fired=true;}assert.ok(fired);});
