import test from 'node:test';import assert from 'node:assert/strict';import {OperatorGate,ClapResetGate} from '../interaction-flow.mjs';
const h=(x,side='Left',extra={})=>({wx:x,wy:.5,px:x,py:.4,handLabel:side,pinch:1,open:true,palmOpen:true,extended:4,brakeCandidate:false,size:.15,depthQuality:1,points:[],...extra});
test('no pose: single labelled open hand is acquired after 700ms, not immediately',()=>{const g=new OperatorGate();assert.equal(g.update([h(.3)],null,0).length,0);for(let t=100;t<700;t+=100)assert.equal(g.update([h(.3)],null,t).length,0);assert.equal(g.update([h(.3)],null,699).length,0);assert.equal(g.update([h(.3)],null,700).length,1);assert.ok(g.handOnly);});
test('hand-only keeps main across array reorder, allows one opposite auxiliary only in dual',()=>{const g=new OperatorGate();for(let t=0;t<=700;t+=100)g.update([h(.3)],null,t);assert.equal(g.update([h(.7,'Right'),h(.3)],null,733).length,1);assert.equal(g.update([h(.7,'Right'),h(.3)],null,766,{dual:true}).length,2);assert.equal(g.update([h(.7,'Right')],null,799,{dual:true}).length,0);});
test('ambiguous hands cannot initialize fallback, long hand loss latches reset',()=>{const g=new OperatorGate();for(let t=0;t<1500;t+=50)assert.equal(g.update([h(.3),h(.7,'Right')],null,t).length,0);for(let t=1500;t<=2200;t+=100)g.update([h(.3)],null,t);assert.equal(g.update([],null,3000).length,0);assert.ok(g.blocked);assert.equal(g.update([h(.3)],null,3033).length,0);});
test('fallback when shoulders exist but wrists invisible',()=>{const g=new OperatorGate(),p=Array.from({length:33},()=>({x:.5,y:.4,visibility:0}));p[11]={x:.4,y:.3,visibility:1};p[12]={x:.6,y:.3,visibility:1};for(let t=0;t<700;t+=100)g.update([h(.3)],p,t);assert.equal(g.update([h(.3)],p,700).length,1);assert.ok(g.handOnly);});
const pair=(d,extra={})=>[h(.5-d/2,'Left',extra),h(.5+d/2,'Right',extra)];
test('edge-on closing palms tolerate spurious pinch after neutral arming',()=>{const c=new ClapResetGate();assert.equal(c.update(pair(.4),0,true),false);assert.equal(c.update(pair(.3),33,true),false);assert.equal(c.update(pair(.18,{down:true,pinch:.1,open:false}),66,true),false);assert.equal(c.update(pair(.10,{down:true,pinch:.1,open:false}),99,true),true);});
test('brief occlusion preserves approach; missing alone never resets',()=>{const c=new ClapResetGate();c.update(pair(.4),0,true);c.update(pair(.25),33,true);assert.equal(c.update([],66,true),false);assert.equal(c.update(pair(.10),100,true),true);const n=new ClapResetGate();n.update(pair(.4),0,true);n.update(pair(.25),33,true);assert.equal(n.update([],400,true),false);assert.equal(n.update(pair(.05),433,true),false);});
test('pinched two-hand zoom and folded fingers cannot arm clap',()=>{for(const extra of [{down:true,pinch:.1,open:false},{extended:1,palmOpen:false}]){const c=new ClapResetGate();for(const [i,d] of [.4,.3,.18,.1].entries())assert.equal(c.update(pair(d,extra),i*33,true),false);}});
test('100 clap cycles and 100 slow closings are deterministic synthetic evidence only',()=>{for(let k=0;k<100;k++){const c=new ClapResetGate();let fires=0;for(const [i,d] of [.4,.35,.25,.18,.10].entries())fires+=Number(c.update(pair(d),i*33,true));assert.equal(fires,1);const n=new ClapResetGate();for(let i=0;i<30;i++)assert.equal(n.update(pair(.4-i*.012),i*100,true),false);}});

test('armed clap is cancelled while a grip owns input and cannot fire after release',()=>{const c=new ClapResetGate();c.update(pair(.4),0,true);c.update(pair(.3),33,true);assert.equal(c.update(pair(.2,{down:true}),66,false),false);assert.equal(c.update(pair(.10,{down:true}),99,false),false);assert.equal(c.update(pair(.10),132,true),false);});
test('long inference gap cannot count as a stable fallback hold',()=>{const g=new OperatorGate();g.update([h(.3)],null,0);assert.equal(g.update([h(.3)],null,800).length,0);assert.equal(g.handOnly,false);for(let t=900;t<=1500;t+=100)g.update([h(.3)],null,t);assert.ok(g.handOnly);});
