import {createRequire} from 'node:module';import {writeFile,mkdir} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const browser=await chromium.launch({headless:true,channel:'msedge',args:['--use-fake-device-for-media-stream','--enable-unsafe-swiftshader']});
const checks=[],errors=[],external=[];let failure,page;
const pass=name=>{checks.push({name,status:'PASS'});console.log('PASS '+name);};const near=(a,b,e=.003)=>assert.ok(Math.abs(a-b)<e,`${a} vs ${b}`);
try{
 const context=await browser.newContext({viewport:{width:1440,height:960},permissions:['camera']});page=await context.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:8796'))external.push(r.url());});
 await page.route('**/vendor/vision_bundle.mjs',r=>r.fulfill({contentType:'text/javascript',body:"export const FilesetResolver={forVisionTasks:async()=>({})};export const HandLandmarker={createFromOptions:async()=>({detectForVideo:()=>({landmarks:window.__hands||[],handedness:(window.__sides||[]).map(side=>[{categoryName:side,score:1}])}),close(){}})};export const PoseLandmarker={createFromOptions:async()=>({detectForVideo:()=>{if(window.__noPose)return {landmarks:[]};const p=Array.from({length:33},()=>({x:.5,y:.55,z:0,visibility:1}));p[11]={x:.4,y:.35,visibility:1};p[12]={x:.6,y:.35,visibility:1};p[15]={x:.3,y:.5,visibility:0};p[16]={x:.7,y:.5,visibility:0};(window.__hands||[]).forEach((h,i)=>{const side=window.__sides?.[i]||'Left';if(side==='Left')p[15]={...h[0],visibility:1};if(side==='Right')p[16]={...h[0],visibility:1};});return {landmarks:[p]};},close(){}})};"}));
 await page.goto('http://127.0.0.1:8796');await page.waitForFunction(()=>window.holoSnapshot?.().anatomy.ready,null,{timeout:60000});
 const snap=()=>page.evaluate(()=>holoSnapshot()),tick=ms=>page.waitForTimeout(ms),buttonPoint=async selector=>{const b=await page.locator(selector).boundingBox();assert.ok(b,selector);return {x:b.x+b.width/2,y:b.y+b.height/2};};
 async function hands(specs,ms=130,expectPinch=true){await page.evaluate(specs=>{const lab=document.getElementById('lab'),v=document.getElementById('camera'),scale=Math.min(lab.clientWidth/v.videoWidth,lab.clientHeight/v.videoHeight),ox=(lab.clientWidth-v.videoWidth*scale)/2,oy=(lab.clientHeight-v.videoHeight*scale)/2;window.__sides=specs.map((s,i)=>s.side|| (i===0?'Left':'Right'));window.__hands=specs.map(({x,y,closed=false,size=1,fist=false,fingerShift=0,oblique=false,curl=0})=>{const ix=1-(x-ox)/(v.videoWidth*scale),iy=(y-oy)/(v.videoHeight*scale),w={x:ix+.02,y:iy+.24,z:0};const p=Array.from({length:21},()=>({...w}));p[1]={x:ix-.035,y:iy+.21,z:0};p[2]={x:ix-.07,y:iy+.16,z:0};p[3]={x:ix-.085,y:iy+.12,z:0};p[4]={x:ix+(closed?.005:-.12),y:iy+(closed?.005:.07),z:0};for(let f=0;f<4;f++){const m=5+f*4,fx=ix+f*.04;for(let j=0;j<4;j++)p[m+j]={x:fx,y:iy+.14-j*.047,z:0};if(fist||(f>0&&f<=curl)){p[m+2]={x:fx,y:iy+.18,z:0};p[m+3]={x:fx,y:iy+.215,z:0};}}if(fist&&closed)p[4]={...p[8],x:p[8].x+.003};if(closed&&fingerShift){p[4].x-=fingerShift/(v.videoWidth*scale);p[8].x-=fingerShift/(v.videoWidth*scale);}const center=[0,5,9,13,17].reduce((a,i)=>({x:a.x+p[i].x/5,y:a.y+p[i].y/5}),{x:0,y:0});return p.map(q=>({x:center.x+(q.x-center.x)*size,y:center.y+(q.y-center.y)*size,z:oblique?(q.x-center.x)*2:0}));});},specs);await tick(ms+180);}

 async function tapAt(p){await hands([p],160);await hands([{...p,closed:true}],100);await hands([p],180);}
 const tapButton=async selector=>{await hands([],120);await tick(320);await tapAt(await buttonPoint(selector));};
 async function modelPoint(id){const b=(await snap()).renderSpace.projection[id];assert.ok(b?.visible,id);return {x:(b.left+b.right)/2,y:b.top+(b.bottom-b.top)*.36};}


 await page.locator('#start').click();await page.waitForFunction(()=>holoSnapshot().mode==='camera');let p={x:620,y:350,side:'Left'},q={x:880,y:350,side:'Right'},visitor={x:1300,y:380,side:'Visitor'};
 await hands([p,q,visitor],3400);assert.equal((await snap()).menu,true);assert.equal((await snap()).trackedHands,1);assert.equal((await snap()).operator.mainSlot,'Left');pass('3sec summon chooses one main hand from one pose and ignores visitor');
 await tapAt({...await buttonPoint('#summon-menu [data-action=summon-whole]'),side:'Left'});assert.equal((await snap()).selected,'single');
 await hands([p,q],200);const otherIcon={...await buttonPoint('#mode-rotate'),side:'Right'};await hands([p,otherIcon],200);await hands([p,{...otherIcon,closed:true}],100);await hands([p,otherIcon],160);assert.equal((await snap()).operation,'place');assert.equal((await snap()).trackedHands,1);pass('Auxiliary hand cannot tap modes outside both-hand mode');
 const modePoint={...await buttonPoint('#mode-rotate'),side:'Left'};await tapAt(modePoint);assert.equal((await snap()).operation,'rotate');for(let i=1;i<=16;i++)await hands([{...p,x:modePoint.x+(p.x-modePoint.x)*i/16,y:modePoint.y+(p.y-modePoint.y)*i/16},q],35);await hands([p,q],200);
 const start=(await snap()).objects.single;for(let i=1;i<=6;i++)await hands([{...p,x:p.x+i*8},q],45);p={...p,x:p.x+48};const turned=(await snap()).objects.single;assert.ok(Math.abs(turned.rotation-start.rotation)>.1);await hands([p,{...q,fist:true}],200);assert.equal((await snap()).operation,'rotate');pass('Main palm rotates; other-hand fist cannot take brake ownership');
 await hands([{...p,closed:true,fist:true},q],160,false);assert.equal((await snap()).operation,'inspect');assert.equal((await snap()).phase,'fixed');await hands([p,q],160);assert.equal((await snap()).operation,'inspect');pass('Main fist fixes angle and opening cannot restart');
 await hands([{...p,closed:true},q],200);assert.equal((await snap()).gripping,'single');await hands([{...p,closed:true},{...q,closed:true}],200);assert.equal((await snap()).trackedHands,2);const fixed=(await snap()).objects.single;for(let i=1;i<=4;i++)await hands([{...p,x:p.x-i*10,closed:true},{...q,x:q.x+i*10,closed:true}],60);assert.equal((await snap()).objects.single.rotation,fixed.rotation);assert.ok((await snap()).objects.single.scale>fixed.scale);pass('Same-person second hand is added only in both mode; zoom keeps angle');
 for(let i=1;i<=6;i++)await hands([{...p,x:p.x+i*16,closed:true},{...q,x:q.x-i*16,closed:true}],35);assert.equal((await snap()).stage,'workspace');pass('Armed clap cannot reset workspace during a captured bimanual pinch squeeze');
 await hands([],250);await page.locator('#settings-toggle').click();await page.locator('[data-action=select-panel]').click();await page.locator('#settings-close').click();assert.equal(await page.locator('#mode-rotate').isDisabled(),true);await page.locator('#mode-dual').click();await page.mouse.move(980,260);await page.mouse.down();await page.mouse.move(950,280,{steps:4});await page.mouse.up();assert.equal((await snap()).objects.panel.rotation,0);assert.equal((await snap()).objects.panel.tilt,0);assert.equal((await snap()).objects.panel.roll,0);pass('Floating panel has no rotation in modes or mouse drag');
 await page.locator('#settings-toggle').click();await page.locator('[data-action=select-single]').click();await page.locator('#settings-close').click();await page.locator('#mode-inspect').click();
 p={x:510,y:350,side:'Left'};q={x:910,y:350,side:'Right'};await hands([p,q],200);for(let i=1;i<=6;i++){await hands([{...p,x:510+i*31},{...q,x:910-i*31}],-140);if((await snap()).stage==='lobby')break;}
 assert.equal((await snap()).stage,'lobby');assert.equal((await snap()).selected,null);assert.equal((await snap()).operation,'place');assert.equal((await snap()).compare,false);assert.equal((await snap()).cameraActive,true);assert.equal((await snap()).objects.panel.rotation,0);pass('One visual clap in both mode resets all and returns to summon screen without stopping camera');
 await page.evaluate(()=>window.__noPose=true);await hands([p,q],1400);assert.equal((await snap()).operator.blocked,true);await page.evaluate(()=>window.__noPose=false);await hands([p,q],200);assert.equal((await snap()).operator.blocked,true);assert.equal((await snap()).trackedHands,0);pass('Long person disappearance blocks returning hands until explicit operator reset');await page.locator('#settings-toggle').click();await page.locator('[data-action=operator-reset]').click();assert.equal((await snap()).operator.blocked,false);assert.equal((await snap()).stage,'lobby');pass('Operator reset button restores the initial screen');
 await page.evaluate(()=>window.__noPose=true);await hands([],500);await page.locator('#settings-toggle').click();await page.locator('[data-action=operator-reset]').click();await hands([{x:620,y:350,side:'Left'}],4200);assert.equal((await snap()).menu,true);assert.equal((await snap()).operator.handOnly,true);pass('No body pose: hand-only fallback summons menu with labelled main hand');await page.evaluate(()=>window.__noPose=false);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.screenshot({path:'tests/results/v13-workspace.png'});pass('No errors or external asset requests');
}catch(e){failure=e;console.error(e);if(page){console.error(JSON.stringify(await page.evaluate(()=>window.holoSnapshot?.()).catch(()=>null)));await page.screenshot({path:'tests/results/v13-failure.png'}).catch(()=>{});}}
finally{await mkdir('tests/results',{recursive:true});await writeFile('tests/results/v13-browser.json',JSON.stringify({checks,errors,externalRequests:external,failure:failure?.stack||null,physicalCameraVerified:false},null,2));await browser.close();}if(failure)process.exitCode=1;
