import test from 'node:test';import assert from 'node:assert/strict';import {handCropRects,remapHandResult,mergeHandResults,describeHand} from '../gestures.mjs';import {OperatorGate} from '../interaction-flow.mjs';
const pose=(center=.5,width=.2)=>{const p=Array.from({length:33},()=>({x:center,y:.5,visibility:0}));p[11]={x:center-width/2,y:.3,visibility:1};p[12]={x:center+width/2,y:.3,visibility:1};p[15]={x:.3,y:.5,visibility:1};p[16]={x:.7,y:.5,visibility:1};return p;};
const h=(x=.3,extra={})=>({wx:1-x,wy:.5,px:1-x,py:.5,open:true,palmOpen:true,brakeCandidate:false,size:.15,depthQuality:1,handLabel:'Left',points:[],...extra});
test('wrist crops use raw pixel coordinates and remain inside frame',()=>{for(const [w,ht] of [[1280,720],[640,480],[720,1280]]){const p=pose();p[15].x=0;p[16].x=1;for(const c of handCropRects(p,w,ht)){assert.ok(c.left>=0&&c.top>=0);assert.ok(c.left+c.width<=w+.001&&c.top+c.height<=ht+.001);assert.equal(c.width,c.height);}}assert.deepEqual(handCropRects(null,1280,720),[]);});
test('crop output maps back without mirror or aspect distortion',()=>{const pts=Array.from({length:21},()=>({x:.25,y:.75,z:-.1}));const r=remapHandResult({landmarks:[pts],handedness:[[{categoryName:'Left'}]]},{left:100,top:200,width:300,height:300},1280,720);assert.equal(r.landmarks[0][0].x,175/1280);assert.equal(r.landmarks[0][0].y,425/720);assert.equal(r.landmarks[0][0].z,-30/1280);assert.equal(r.handedness[0][0].categoryName,'Left');});
test('full frame and overlapping ROIs cannot duplicate a hand',()=>{const pts=x=>Array.from({length:21},()=>({x,y:.5,z:0}));const r=mergeHandResults([{landmarks:[pts(.3)]},{landmarks:[pts(.305),pts(.7)]}],1280,720);assert.equal(r.landmarks.length,2);});
test('pose jitter before a main hand is chosen cannot permanently lock lobby',()=>{const g=new OperatorGate();g.update([],pose(.5,.2),0);g.update([],pose(.75,.4),33);assert.equal(g.blocked,false);assert.equal(g.update([h()],pose(.5,.2),66,{lobby:true}).length,1);});
test('lobby recovers blocked initial input, active workspace still fails closed',()=>{const g=new OperatorGate();g.update([h()],pose(),0);g.update([h()],pose(.8,.2),33);assert.ok(g.blocked);assert.equal(g.update([h()],pose(),66).length,0);assert.equal(g.update([h()],pose(),99,{lobby:true}).length,1);assert.equal(g.blocked,false);});
test('one open hand can initialize fallback while the other holds a phone',()=>{const g=new OperatorGate();for(let t=0;t<=700;t+=100)g.update([h(.3),h(.7,{handLabel:'Right',open:false,palmOpen:false,brakeCandidate:true})],null,t);assert.ok(g.handOnly);assert.equal(g.mainSlot,'Left');});
test('two open strangers still cannot initialize pose-free fallback',()=>{const g=new OperatorGate();for(let t=0;t<2000;t+=100)assert.equal(g.update([h(.3),h(.7,{handLabel:'Right'})],null,t).length,0);assert.equal(g.handOnly,false);});

test('single-hand rescue only samples the selected body wrist; bimanual rescue samples both',()=>{assert.equal(handCropRects(pose(),1280,720,'Right').length,1);assert.equal(handCropRects(pose(),1280,720,'Right')[0].wrist,16);assert.equal(handCropRects(pose(),1280,720).length,2);});
